### ISSUE TITLE
Add option to keep approximate note range

### ISSUE THREAD

**Issue by ThePython10110** [1j01/midiflip#1]
"It would be good to be able to look at the original song as a whole in order to transpose notes back to reasonable ranges like [Automatic MIDI Inverter](https://midi-inverter.herokuapp.com/) does... (You can only look at and change a single note at a time with the current API.)"

I don't know how easy this would be, but I would do it this way:
1. Keep track of the highest/lowest note in a channel as they are processed
2. Calculate which octave would be closest.
3. Go through again and transpose it to the closest octave.

This way, not much needs to be changed (it just needs another pass). And then of course another command line option for that (it wouldn't affect percussion).

**Comment by ThePython10110** [comment]
[I just decided to do it myself.](https://github.com/thepython10110/midiflip)

**Comment by 1j01** [comment]
I'm glad you were able to implement it. However, you're not meant to overwrite the authorship information when forking a project. If you read the license, it says "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."
You can add your name like "Copyright 2017 by Isaiah Odhner, and 2023 by ThePython10110" if you want.

**Comment by ThePython10110** [comment]
Sorry about that. I'm incredibly new to this kind of thing. I'll fix it as soon as I have time.
